### ISSUE TITLE
Plugin fails when vagrant-aws is installed

### ISSUE THREAD

**Issue by jhulten** [WhoopInc/vagrant-s3auth#12] opened 2015-03-10 23:50 UTC
Plugin does not call the AWS SDK from the global namespace and fails when `VagrantPlugins::AWS` exists.

Working on patch now.

```
Bringing machine 'default' up with 'vmware_fusion' provider...
==> default: Box 'REDACTED/dev-vm' could not be found. Attempting to find and install...
    default: Box Provider: vmware_desktop, vmware_fusion, vmware_workstation
    default: Box Version: >= 0
==> default: Loading metadata for box 'REDACTED/dev-vm'
    default: URL: https://atlas.hashicorp.com/REDACTED/dev-vm
==> default: Adding box 'REDACTED/dev-vm' (v15.069.0) for provider: vmware_desktop
    default: Downloading: https://atlas.hashicorp.com/REDACTED/boxes/dev-vm/versions/REDACTED/providers/vmware_desktop.box
~/.vagrant.d/gems/gems/vagrant-s3auth-1.0.2/lib/vagrant-s3auth/util.rb:30:in `s3_object_for': uninitialized constant VagrantPlugins::AWS::S3 (NameError)
        from ~/.vagrant.d/gems/gems/vagrant-s3auth-1.0.2/lib/vagrant-s3auth/util.rb:35:in `s3_object_for'
        from ~/.vagrant.d/gems/gems/vagrant-s3auth-1.0.2/lib/vagrant-s3auth/extension/downloader.rb:17:in `execute_curl_with_s3'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/util/downloader.rb:133:in `download!'
        from /opt/vagrant/embedded/gems/gems/vagrant-1.7.2/lib/vagrant/action/builtin/box_add.rb:432:in `download'
<SNIP>
```

**Comment by benesch** [comment] 2015-03-11 00:11
Dupe of #11!

**Comment by jhulten** [comment] 2015-03-11 00:23
Yup. My bad.

Status on #11? Seems the PR doesn't have access to the AWS credentials in Travis...

**Comment by benesch** [comment] 2015-03-11 02:25
Committed and pushed. Waiting on Travis to verify to cut a new release.

**Comment by benesch** [comment] 2015-03-11 02:39
Deployed as v1.0.3. Thanks for the ping!

**Closed by benesch** 2015-03-11 02:39 UTC
